# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RU5MAXEH4S_5r0Z7bR6n6QKinRI6QZST
"""

import pandas as pd

print("---Ejercicio 1---")
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
pos = [0, 4, 8, 14, 20]

for i in pos:
  print(ser[i])

print("---Ejercicio 2---")
ser = pd.Series(['how', 'to', 'kick', 'ass?'])
for i in range(len(ser)):
  print(str(i) + " " + str(len(ser[i])))

print("---Ejercicio 3---")
ser = pd.Series(['Apple', 'Orange', 'Plan', 'Python', 'Money'])
pos = "aeiouAEIOU"
ct = 0
for i in range(len(ser)):
    ct = 0
    for j in ser[i]:
        if j in pos:
            ct += 1
        if ct > 1:
            print(str(i) + " " + ser[i])
            break